apiVersion: v1
kind: ConfigMap
metadata:
  name: cvmfs-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry.contents -}}
  {{- $key | nindent 2 }}: |
    {{- tpl $entry.contents $ | nindent 4 -}}
    {{- end }}
  {{- end }}
